### ISSUE TITLE
Free or not?

### ISSUE THREAD

**Issue by NimoTh** [Falci/slack-anonymous-bot#1]
Hi Falci,

The repository is MIT License. However, https://abot.apki.io/ states I have to pay after two weeks. So, can you clarify, please?

Thanks!
Martin

**Comment by Falci** [comment]
Hi NimoTh,

That's not our app :)

This is our is our app: https://slackanonymous.herokuapp.com
100% free, forever (or while Heroku don't charge me)

**Comment by Falci** [comment]
afaik, MIT means you can use/copy/modify the source for free. Doesn't mean you can use the hosted app for free.

**Comment by NimoTh** [comment]
Uh, I just now see the two look almost the same. Thanks for informing me! I prefer yours :-) Keep it up.
