### ISSUE TITLE
How do you see user identity as an admin?

### ISSUE THREAD

**Issue by karban941** [Falci/slack-anonymous-bot#4]
In the admin instructions in Slack it says that I have permission to do so.

Anonymous Bot can:
View information about the user’s identity, granted by 1 team member
Add actions and/or slash commands that people can use, granted by 1 team member

**Comment by Falci** [comment]
Hi @karban941,

It seems there's a misunderstanding here. Slack says that the bot knows/receive the information about the users. It doesn't mean the bot make it available for other users/admins. Not even developers can access it.

There's a minimum information needed by the bot:

- Team ID + Channel ID: the bot need to know where to send the message
- username/ID: the bot sends a "donation" message. [We keep the ID](https://github.com/Falci/slack-anonymous-bot/blob/master/src/services/advertising.service.ts) (in memory, not in a database) to prevent spam from out side
- The message: obvious, the bot need to receive the text.

Besides the user ID in the cache, we don't have any other information. Also, the cache has a short lifetime (it is cleaned after 100 messages), and there's no way to access the cache info
